# Generated by Django 5.0.6 on 2024-07-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryy', '0002_alter_inventoryitem_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
