# Generated by Django 5.0.6 on 2024-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryy', '0004_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
